# Autogenerated by devscripts/update-version.py

__version__ = '2023.05.15.122435'

RELEASE_GIT_HEAD = '61142ac998d82ad3296ec9d324f4fec7f31dcf9f'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
