# Autogenerated by devscripts/update-version.py

__version__ = '2025.08.09.065402'

RELEASE_GIT_HEAD = 'a1f05974dce2328f3087752493275b681745ac37'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'lockmatrix/yt-dlp'

ORIGIN = 'lockmatrix/yt-dlp'

_pkg_version = '2025.08.09.065402'
