# Autogenerated by devscripts/update-version.py

__version__ = '2024.12.03.062115'

RELEASE_GIT_HEAD = '30be8b0f7e155b8668deab276faebe1646d17502'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'lockmatrix/yt-dlp'

ORIGIN = 'lockmatrix/yt-dlp'

_pkg_version = '2024.12.03.062115'
